# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow
import sys  # 导入sys模块

import mainadmin
from service import service

class Ui_MainWindow(QMainWindow):
    # 构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮
        self.setupUi(self)  # 初始化窗体设置
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(360, 196)
        MainWindow2.setMinimumSize(QtCore.QSize(360, 196))
        MainWindow2.setMaximumSize(QtCore.QSize(360, 196))
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.label.setStyleSheet("border-image: url(:/T1/images/login.jpg);")
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap(":/T1/images/login.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editAdmin = QtWidgets.QLineEdit(self.centralwidget)
        self.editAdmin.setGeometry(QtCore.QRect(143, 90, 141, 20))
        self.editAdmin.setObjectName("editAdmin")
        self.editPwd = QtWidgets.QLineEdit(self.centralwidget)
        self.editPwd.setGeometry(QtCore.QRect(142, 120, 141, 20))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(69, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(150, 150, 61, 23))
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(220, 150, 61, 23))
        self.btnExit.setObjectName("btnExit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 371, 61))
        self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap("../images/login.jpg"))
        self.label_4.setObjectName("label_4")
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        self.btnExit.clicked.connect(MainWindow2.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

        self.retranslateUi(MainWindow2)
        self.btnExit.clicked.connect(MainWindow2.close)  # 关闭登录窗体
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)
        # 输入密码后按回车键执行登录操作
        self.editPwd.editingFinished.connect(self.openMain)
        # 单击“登录”按钮执行登录操作
        self.btnLogin.clicked.connect(self.openMain)


        # 打开主窗体

    def openMain(self):
        service.adminName = self.editAdmin.text()  # 全局变量，记录管理员名
        self.adminpwd = self.editPwd.text()  # 记录管理员密码
        if service.adminName != "" and self.adminpwd != "":  # 判断管理员名和密码不为空
            # 根据管理员名和密码查询数据
            result = service.query("select * from tb_admin where adminname = %s and adminpwd = %s", service.adminName,
                                   self.adminpwd)
            if len(result) > 0:  # 如果查询结果大于0，说明存在该管理员，可以登录
                self.m = mainadmin.Ui_MainWindow()  # 创建主窗体对象
                self.m.show()  # 显示主窗体
                # self.setupUi.MainWindow2.hide()  # 隐藏当前的登录窗体
            else:
                self.editAdmin.setText("")  # 清空管理员名文本
                self.editPwd.setText("")  # 清空密码文本框
                QMessageBox.warning(None, '警告', '请输入正确的管理员名和密码！', QMessageBox.Ok)
        else:
            QMessageBox.warning(None, '警告', '请输入管理员名和密码！', QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "防漏堵漏材料数据库系统管理员权限登录"))
        self.label.setWhatsThis(_translate("MainWindow",
                                           "<html><head/><body><p><img src=\":/newPrefix/images/login.jpg\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "管理员："))
        self.label_3.setText(_translate("MainWindow", "密  码："))
        self.btnLogin.setText(_translate("MainWindow", "登录"))
        self.btnExit.setText(_translate("MainWindow", "退出"))
