# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow
import sys  # 导入sys模块
import main
import userzhuce
from service import service



class Ui_MainWindow(QMainWindow):
    # 构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮
        self.setupUi(self)  # 初始化窗体设置

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 196)
        MainWindow.setMinimumSize(QtCore.QSize(360, 196))
        MainWindow.setMaximumSize(QtCore.QSize(360, 196))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.label.setStyleSheet("border-image: url(:/T1/images/login.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/T1/images/login.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(143, 90, 141, 20))
        self.editName.setObjectName("editName")
        self.editPwd = QtWidgets.QLineEdit(self.centralwidget)
        self.editPwd.setGeometry(QtCore.QRect(142, 120, 141, 20))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(69, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(150, 150, 61, 23))
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(220, 150, 61, 23))
        self.btnExit.setObjectName("btnExit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 371, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/login.jpg"))
        self.label_4.setObjectName("label_4")
        self.btnzhuce = QtWidgets.QPushButton(self.centralwidget)
        self.btnzhuce.setGeometry(QtCore.QRect(80, 150, 61, 23))
        self.btnzhuce.setObjectName("btnzhuce")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnExit.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        self.btnExit.clicked.connect(MainWindow.close)  # 关闭登录窗体
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 输入密码后按回车键执行登录操作
        self.editPwd.editingFinished.connect(self.openMain)
        # 单击“登录”按钮执行登录操作
        self.btnLogin.clicked.connect(self.openMain)
        # 单击“注册”按钮执行登录操作
        self.btnzhuce.clicked.connect(self.openzhuce)

        # 打开主窗体

    def openMain(self):
        try:
            service.userName = self.editName.text()  # 全局变量，记录用户名
            self.userpwd = self.editPwd.text()  # 记录用户密码
            if service.userName != "" and self.userpwd != "":  # 判断用户名和密码不为空
                # 根据用户名和密码查询数据
                result = service.query("select * from tb_user where username = %s and userpwd = %s", service.userName,self.userpwd)
                if len(result) > 0:  # 如果查询结果大于0，说明存在该用户，可以登录
                    self.m = main.Ui_MainWindow()  # 创建主窗体对象
                    self.m.show()  # 显示主窗体
                    MainWindow.hide()  # 隐藏当前的登录窗体
                else:
                    self.editName.setText("")  # 清空用户名文本
                    self.editPwd.setText("")  # 清空密码文本框
                    QMessageBox.warning(None, '警告', '请输入正确的用户名和密码！', QMessageBox.Ok)
            else:
                QMessageBox.warning(None, '警告', '请输入用户名和密码！', QMessageBox.Ok)
        except:
            QMessageBox.warning(None, '警告', '请检查用户名和密码！', QMessageBox.Ok)




    def openzhuce(self):
        self.m = userzhuce.Ui_MainWindow()  # 创建用户维护窗体对象
        self.m.show()  # 显示窗体

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "欢迎使用"))
        self.label.setWhatsThis(_translate("MainWindow",
                                           "<html><head/><body><p><img src=\":/T1/images/login.jpg\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "用户名："))
        self.label_3.setText(_translate("MainWindow", "密  码："))
        self.btnLogin.setText(_translate("MainWindow", "登录"))
        self.btnExit.setText(_translate("MainWindow", "退出"))
        self.btnzhuce.setText(_translate("MainWindow", "注册"))




# 主方法

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程
